allowBuilds:
  '@google/genai': true
  '@prisma/engines': set this to true or false
  bcrypt: set this to true or false
  msgpackr-extract: true
  prisma: set this to true or false
  protobufjs: true
  unrs-resolver: true
